--CREATE A QUEARY FOR JOINING USING THE UNIONS

SELECT * FROM bike_share_yr_0

SELECT * FROM BIKE_SHARE_YR_1

--USING THE UNIONS FOR JOINING BOTH TABLE AND GIVEN RESULT IN ONE TERM

--THERE IS USING UNION ALL MEANS RESTORING THE DUPLICATE VALUES
SELECT * FROM bike_share_yr_0
UNION ALL
SELECT * FROM BIKE_SHARE_YR_1

--THERE IS USING UNION SO STORING WITHOUT DUPLICATE VALUES
SELECT * FROM bike_share_yr_0
UNION
SELECT * FROM BIKE_SHARE_YR_1

SELECT * FROM cost_table


--USING THE CTE
WITH MY_CTE AS(

SELECT * FROM bike_share_yr_0
UNION ALL
SELECT * FROM BIKE_SHARE_YR_1)

SELECT dteday, SEASON, a.YR, WEEKDAY, HR, RIDER_TYPE, RIDERS, PRICE, COGS, RIDERS * PRICE AS REVENUE, RIDERS * PRICE - COGS AS PROFITS
FROM MY_CTE a
LEFT JOIN COST_TABLE b
ON 
a.yr = b.yr
